# Generated by Django 4.1 on 2022-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('level', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_username', models.CharField(max_length=150)),
                ('questions', models.CharField(max_length=100)),
                ('time_started', models.TimeField()),
                ('time_finished', models.TimeField()),
                ('questions_answered', models.IntegerField()),
            ],
        ),
    ]
